package module.Menus;

import module.Logic.Calc;

import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.text.SimpleDateFormat;

/**
 * Created by Biko on 12.03.2016.
 */
public class OptionsMenu {
    private JTextPane sizeOfTheFieldTextPane;
    private JSlider sizeSlider;
    private JPanel jpanel;
    private JTextPane newTilesAfterEveryTextPane;
    private JSlider spawnSlider;
    private JLabel ImageLabel;
    private JTextPane rangeOfValuesThatTextPane;
    private JSlider rangeSlider;
    private JButton backButton;

    public OptionsMenu() {

        JFrame frame = new JFrame("Menu");
        $$$setupUI$$$();
        spawnSlider.setValue(Calc.getSpawnRate());
        sizeSlider.setValue(Calc.getTableSize());
        rangeSlider.setValue(Calc.getRange());
        frame.setContentPane(jpanel);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);

        frame.setLocationRelativeTo(null);
        rangeSlider.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                Calc.setRange(rangeSlider.getValue());
            }
        });
        sizeSlider.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                Calc.setTableSize(sizeSlider.getValue());
            }
        });
        spawnSlider.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                Calc.setSpawnRate(spawnSlider.getValue());
            }
        });
        backButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (e.getSource() == backButton) { // delete the comment to making some change tp push
                    frame.dispose();
                }
            }
        });
    }


    public static void main(String[] args) {
        OptionsMenu oM = new OptionsMenu();
    }


    private void createUIComponents() {
        try {
            ImageLabel = new JLabel(new ImageIcon(ImageIO.read(getClass().getResource("/resources/banner.png"))));
        } catch (IOException e) {
            e.printStackTrace();
        }
        rangeSlider = new JSlider(2, 128, 2);


    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        jpanel = new JPanel();
        jpanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(8, 1, new Insets(10, 10, 10, 10), -1, -1));
        jpanel.setBackground(new Color(-1180929));
        jpanel.setEnabled(true);
        jpanel.setFont(new Font("Segoe Script", jpanel.getFont().getStyle(), jpanel.getFont().getSize()));
        jpanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(0, 10, 10, 0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font(jpanel.getFont().getName(), jpanel.getFont().getStyle(), jpanel.getFont().getSize()), new Color(-4473925)));
        sizeOfTheFieldTextPane = new JTextPane();
        sizeOfTheFieldTextPane.setEditable(true);
        sizeOfTheFieldTextPane.setEnabled(true);
        sizeOfTheFieldTextPane.setFont(new Font("BankGothic Lt BT", sizeOfTheFieldTextPane.getFont().getStyle(), sizeOfTheFieldTextPane.getFont().getSize()));
        sizeOfTheFieldTextPane.setText("Size of the Field:");
        jpanel.add(sizeOfTheFieldTextPane, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTH, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 20), null, 0, false));
        newTilesAfterEveryTextPane = new JTextPane();
        newTilesAfterEveryTextPane.setFont(new Font("BankGothic Lt BT", newTilesAfterEveryTextPane.getFont().getStyle(), newTilesAfterEveryTextPane.getFont().getSize()));
        newTilesAfterEveryTextPane.setText("New tiles after every turn:");
        jpanel.add(newTilesAfterEveryTextPane, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTH, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 20), null, 0, false));
        spawnSlider = new JSlider();
        spawnSlider.setEnabled(true);
        spawnSlider.setExtent(0);
        spawnSlider.setFont(new Font(spawnSlider.getFont().getName(), spawnSlider.getFont().getStyle(), spawnSlider.getFont().getSize()));
        spawnSlider.setMajorTickSpacing(1);
        spawnSlider.setMaximum(20);
        spawnSlider.setMinimum(1);
        spawnSlider.setMinorTickSpacing(1);
        spawnSlider.setOrientation(0);
        spawnSlider.setPaintLabels(true);
        spawnSlider.setPaintTicks(true);
        spawnSlider.setSnapToTicks(true);
        spawnSlider.setValue(4);
        spawnSlider.setValueIsAdjusting(true);
        jpanel.add(spawnSlider, new com.intellij.uiDesigner.core.GridConstraints(5, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTHWEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ImageLabel.setText("");
        jpanel.add(ImageLabel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        sizeSlider = new JSlider();
        sizeSlider.setInverted(false);
        sizeSlider.setMajorTickSpacing(5);
        sizeSlider.setMaximum(25);
        sizeSlider.setMinimum(2);
        sizeSlider.setMinorTickSpacing(1);
        sizeSlider.setPaintLabels(true);
        sizeSlider.setPaintTicks(true);
        sizeSlider.setValue(4);
        jpanel.add(sizeSlider, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTHWEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        rangeSlider = new JSlider();
        rangeSlider.setEnabled(true);
        rangeSlider.setInverted(false);
        rangeSlider.setMajorTickSpacing(8);
        rangeSlider.setMaximum(128);
        rangeSlider.setMinimum(2);
        rangeSlider.setMinorTickSpacing(2);
        rangeSlider.setPaintLabels(true);
        rangeSlider.setPaintTicks(true);
        rangeSlider.setSnapToTicks(true);
        rangeSlider.setValue(10);
        jpanel.add(rangeSlider, new com.intellij.uiDesigner.core.GridConstraints(7, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTH, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        rangeOfValuesThatTextPane = new JTextPane();
        rangeOfValuesThatTextPane.setFont(new Font("BankGothic Lt BT", rangeOfValuesThatTextPane.getFont().getStyle(), rangeOfValuesThatTextPane.getFont().getSize()));
        rangeOfValuesThatTextPane.setText("Range of Values that can spawn:");
        jpanel.add(rangeOfValuesThatTextPane, new com.intellij.uiDesigner.core.GridConstraints(6, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTH, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 20), null, 0, false));
        backButton = new JButton();
        backButton.setHideActionText(false);
        backButton.setHorizontalAlignment(0);
        backButton.setHorizontalTextPosition(4);
        backButton.setText("Back");
        jpanel.add(backButton, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return jpanel;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */


}
