package module.Menus;

import module.Logic.Calc;
import oracle.jrockit.jfr.JFR;

import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;

/**
 * Created by Biko on 12.03.2016.
 */
public class OptionsMenu extends JFrame {
    private JTextPane sizeOfTheFieldTextPane;
    private JTextPane newTilesAfterEveryTextPane;
    private JTextPane rangeOfValuesThatTextPane;
    private JSlider sizeSlider;
    private JPanel jpanel;
    private JSlider spawnSlider;
    private JLabel ImageLabel;
    private JSlider rangeSlider;
    private JButton backButton;

    public OptionsMenu() {
        spawnSlider.setValue(Calc.getSpawnRate());
        sizeSlider.setValue(Calc.getTableSize());
        rangeSlider.setValue(Calc.getRange());
        setContentPane(jpanel);
        setUndecorated(true);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        pack();
        setVisible(true);

        setLocationRelativeTo(null);
        rangeSlider.addChangeListener(e -> Calc.setRange(rangeSlider.getValue()));
        sizeSlider.addChangeListener(e -> Calc.setTableSize(sizeSlider.getValue()));
        spawnSlider.addChangeListener(e -> Calc.setSpawnRate(spawnSlider.getValue()));
        backButton.addActionListener(e -> {
            if (e.getSource() == backButton) { // delete the comment to making some change tp push
                dispose();
            }
        });
    }


    public static void main(String[] args) {
        OptionsMenu oM = new OptionsMenu();
    }


    private void createUIComponents() {
        try {
            ImageLabel = new JLabel(new ImageIcon(ImageIO.read(getClass().getResource("/resources/banner.png"))));
        } catch (IOException e) {
            e.printStackTrace();
        }



    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */


}
